# Generated by Django 3.2.12 on 2022-02-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20220202_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_efficiency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
